---
name: CommandShop
author: BoxOfDevs Team
version: 1.0.0
main: BoxOfDevs\CommandShop\CommandShop
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0]
softdepend: EconomyAPI
permissions:
  cshop:
    default: op
    description: "Main permission for CommandShop"
    children:
      cshop.command.manage:
        default: op
        description: "Permission for '/cshop'"
      cshop.breaksign:
        default: op
        description: "Permission for breaking CommandShop signs"
      cshop.buy:
        default: op
        description: "Permission for 'buying' commands via '/buycmd' AND via signs"
        children:
          cshop.buy.command:
            default: true
            description: "Permission for 'buying' commands via '/buycmd'"
          cshop.buy.sign:
            default: true
            description: "Permission for 'buying' commands via signs"
...
